# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
output: walletaddresserver/types.go
generate:
  models: true
output-options:
  skip-prune: true
